
# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'My name is'
description: 'Ko Young Sun, 24years'

# Images
avatar: 'KakaoTalk_Photo_2024-06-20-17-43-46.jpeg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
facebook: 'myfacebook'
twitter: 'mytwitter'
youtube: 'myyoutube'
github-user: 'mygithub'
tumblr: 'mytumblr'
weibo: 'myweibo'
vk: 'myvk'
blog_url: 'myblog.blog.com'
email: 'hello@example.com'
messenger: 'myfbchat'

social-links-order: [java, javascript, python, c-lang, html5, css3]

# Yaml manifest of supported social links
social-links:
  - name: java
    url-pattern: '#'
    icon-class: fab fa-2x fa-java

  - name: javascript
    url-pattern: '#'
    icon-class: fab fa-2x fa-js

  - name: python
    url-pattern: '#'
    icon-class: fab fa-2x fa-python

  - name: c-lang
    url-pattern: '#'
    icon-class: fab fa-2x fa-cuttlefish

  - name: html5
    url-pattern: '#'
    icon-class: fab fa-2x fa-html5

  - name: css3
    url-pattern: '#'
    icon-class: fab fa-2x fa-css3-alt
